import { useEffect, useMemo, useState } from 'react'
import { ArrowLeftRight, Check, Coins, Search, X } from 'lucide-react'
import { queryCollection, queryFriendCollection } from './cardsApi'
import { createTrade, getFriends } from './tradeApi'
import GameCard from './GameCard'
import type { Card, Friend, Rarity } from './types'

export type TradeDraft={contact?:string;requestedCards?:Card[]}
const rarities:Rarity[]=['L','UR','SR','R','PC','C']

export default function TradeComposer({currentUserId,draft,onClose,onSent}:{currentUserId:string;draft?:TradeDraft;onClose:()=>void;onSent:()=>void}){
 const [friends,setFriends]=useState<Friend[]>([]);const [friend,setFriend]=useState<Friend|null>(null)
 const [mine,setMine]=useState<Card[]>([]);const [theirs,setTheirs]=useState<Card[]>(draft?.requestedCards??[]);const [mineTotal,setMineTotal]=useState(0);const [theirsTotal,setTheirsTotal]=useState(0)
 const [knownCards,setKnownCards]=useState(()=>new Map((draft?.requestedCards??[]).map(card=>[card.id,card])))
 const [offered,setOffered]=useState<string[]>([]);const [requested,setRequested]=useState<string[]>(draft?.requestedCards?.map(card=>card.id)??[]);const [tab,setTab]=useState<'mine'|'theirs'>('theirs')
 const [mineQuery,setMineQuery]=useState('');const [theirQuery,setTheirQuery]=useState('');const [mineDebounced,setMineDebounced]=useState('');const [theirDebounced,setTheirDebounced]=useState('');const [mineRarity,setMineRarity]=useState<Rarity|undefined>();const [theirRarity,setTheirRarity]=useState<Rarity|undefined>();const [minePage,setMinePage]=useState(0);const [theirPage,setTheirPage]=useState(0)
 const [credits,setCredits]=useState(0);const [requestedCredits,setRequestedCredits]=useState(0);const [creditsOpen,setCreditsOpen]=useState(false);const [loadingMine,setLoadingMine]=useState(false);const [loadingTheirs,setLoadingTheirs]=useState(false);const [loadingFriends,setLoadingFriends]=useState(true);const [sending,setSending]=useState(false);const [error,setError]=useState('');const [confirming,setConfirming]=useState(false)
 useEffect(()=>{const timer=setTimeout(()=>setMineDebounced(mineQuery.trim()),400);return()=>clearTimeout(timer)},[mineQuery]);useEffect(()=>{const timer=setTimeout(()=>setTheirDebounced(theirQuery.trim()),400);return()=>clearTimeout(timer)},[theirQuery])
 useEffect(()=>setMinePage(0),[mineDebounced,mineRarity]);useEffect(()=>setTheirPage(0),[theirDebounced,theirRarity])
 useEffect(()=>{getFriends(currentUserId).then(items=>{setFriends(items);setFriend(items.find(item=>item.username===draft?.contact)??(draft?.contact?null:items[0]??null))}).catch(()=>setError('Impossible de charger vos amis.')).finally(()=>setLoadingFriends(false))},[currentUserId,draft?.contact])
 useEffect(()=>{let active=true;setLoadingMine(true);queryCollection({page:minePage,query:mineDebounced,rarity:mineRarity}).then(data=>{if(active){setMine(data.cards);setMineTotal(data.total);setKnownCards(current=>new Map([...current,...data.cards.map(card=>[card.id,card] as const)]))}}).catch(()=>active&&setError('Impossible de charger votre collection.')).finally(()=>active&&setLoadingMine(false));return()=>{active=false}},[minePage,mineDebounced,mineRarity])
 useEffect(()=>{if(!friend)return;let active=true;setLoadingTheirs(true);queryFriendCollection(friend.username,{page:theirPage,query:theirDebounced,rarity:theirRarity}).then(data=>{if(active){const visible=theirPage===0?[...new Map([...(draft?.requestedCards??[]),...data.cards].map(card=>[card.id,card])).values()]:data.cards;setTheirs(visible);setKnownCards(current=>new Map([...current,...visible.map(card=>[card.id,card] as const)]));setTheirsTotal(current=>theirPage===0?Math.max(data.total,!theirDebounced&&!theirRarity?(draft?.requestedCards?.length??0):0):current)}}).catch(()=>active&&setError('Impossible de charger la collection de votre ami.')).finally(()=>active&&setLoadingTheirs(false));return()=>{active=false}},[friend,theirPage,theirDebounced,theirRarity,draft?.requestedCards])
 const shown=tab==='mine'?mine:theirs;const selected=tab==='mine'?offered:requested;const query=tab==='mine'?mineQuery:theirQuery;const rarity=tab==='mine'?mineRarity:theirRarity;const page=tab==='mine'?minePage:theirPage;const total=tab==='mine'?mineTotal:theirsTotal;const loading=tab==='mine'?loadingMine:loadingTheirs
 const selectedMineCards=useMemo(()=>offered.map(id=>knownCards.get(id)).filter((card):card is Card=>Boolean(card)),[offered,knownCards]);const selectedTheirCards=useMemo(()=>requested.map(id=>knownCards.get(id)).filter((card):card is Card=>Boolean(card)),[requested,knownCards])
 const setQuery=(value:string)=>tab==='mine'?setMineQuery(value):setTheirQuery(value);const setRarity=(value:Rarity|undefined)=>tab==='mine'?setMineRarity(value):setTheirRarity(value);const setPage=(value:number)=>tab==='mine'?setMinePage(value):setTheirPage(value)
 const toggle=(id:string)=>tab==='mine'?setOffered(list=>list.includes(id)?list.filter(item=>item!==id):[...list,id]):setRequested(list=>list.includes(id)?list.filter(item=>item!==id):[...list,id])
 const send=async()=>{if(!friend)return;if(!offered.length&&!requested.length&&!credits&&!requestedCredits){setError('Sélectionnez au moins une carte ou des wikibidous.');return}if(offered.length+requested.length>100){setError('Un échange ne peut pas inclure plus de 100 cartes.');return}if(!confirming){setConfirming(true);return}setSending(true);setError('');try{await createTrade({recipientId:friend.id,currentUserId,offeredCardIds:offered,requestedCardIds:requested,offeredCredits:credits,requestedCredits});onSent()}catch(err){setError(err instanceof Error?err.message:'Envoi impossible.');setConfirming(false)}finally{setSending(false)}}
 if(!friend)return <div className="modal-backdrop"><section className="friend-picker" role="dialog" aria-modal="true"><button className="modal-x" onClick={onClose}><X/></button><h2>Choisir un ami</h2>{loadingFriends?<p>Chargement…</p>:friends.length?friends.map(item=><button key={item.id} onClick={()=>setFriend(item)}><i>{item.username[0]}</i>{item.username}<span>Échanger →</span></button>):<p>Aucun ami disponible.</p>}</section></div>
 return <div className="modal-backdrop trade-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className="trade-composer" role="dialog" aria-modal="true" aria-labelledby="trade-title"><header><h2 id="trade-title">Échanger avec <span>{friend.username}</span></h2><button onClick={onClose} aria-label="Fermer"><X/></button></header>
  <div className="trade-summary"><b>Moi : {offered.length} carte{offered.length!==1?'s':''}{credits?` · ${credits} WB`:''}</b><ArrowLeftRight/><b>{friend.username} : {requested.length} carte{requested.length!==1?'s':''}{requestedCredits?` · ${requestedCredits} WB`:''}</b></div>
  <nav><button className={tab==='mine'?'active':''} onClick={()=>setTab('mine')}>Mes cartes</button><button className={tab==='theirs'?'active':''} onClick={()=>setTab('theirs')}>Cartes de {friend.username}</button></nav>
  {selectedMineCards.length||selectedTheirCards.length?<div className="trade-selected">{selectedMineCards.length?<section><strong>Je propose</strong>{selectedMineCards.map(card=><button key={card.id} onClick={()=>setOffered(items=>items.filter(id=>id!==card.id))}><GameCard card={card} compact/><X/></button>)}</section>:null}{selectedTheirCards.length?<section><strong>Je demande</strong>{selectedTheirCards.map(card=><button key={card.id} onClick={()=>setRequested(items=>items.filter(id=>id!==card.id))}><GameCard card={card} compact/><X/></button>)}</section>:null}</div>:null}
  <div className="trade-tools"><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Rechercher par titre ou catégorie…"/></label><select aria-label="Rareté" value={rarity??''} onChange={event=>setRarity((event.target.value||undefined) as Rarity|undefined)}><option value="">Rareté</option>{rarities.map(value=><option key={value}>{value}</option>)}</select><button className={creditsOpen?'active':''} onClick={()=>setCreditsOpen(value=>!value)}><Coins/>Ajouter des WB</button></div>
  {creditsOpen?<div className="trade-credits"><label>Vous ajoutez <input type="number" min="0" max="10000" value={credits} onChange={e=>setCredits(Math.min(10000,Math.max(0,Number(e.target.value))))}/> WB</label><ArrowLeftRight/><label>{friend.username} ajoute <input type="number" min="0" max="10000" value={requestedCredits} onChange={e=>setRequestedCredits(Math.min(10000,Math.max(0,Number(e.target.value))))}/> WB</label></div>:null}
  {error?<div className="api-error">{error}</div>:null}<div className="trade-card-area"><div className="trade-card-grid">{loading?<p>Chargement de la collection…</p>:shown.map(card=>{const active=selected.includes(card.id);return <button key={card.id} className={active?'selected':''} onClick={()=>toggle(card.id)}><GameCard card={card} compact/>{active?<span className="trade-check"><Check/></span>:null}</button>})}</div>{!loading&&!shown.length?<div className="trade-no-card">Aucune carte trouvée.</div>:null}<div className="trade-pagination"><button disabled={page===0||loading} onClick={()=>setPage(Math.max(0,page-1))}>← Précédent</button><span>Page {page+1} sur {Math.max(1,Math.ceil(total/50))}</span><button disabled={loading||(page+1)*50>=total} onClick={()=>setPage(page+1)}>Suivant →</button></div></div>
  <footer><button onClick={onClose}>Annuler</button>{confirming?<span>Confirmer l’envoi de cette offre ?</span>:null}<button className="primary" disabled={sending} onClick={send}><ArrowLeftRight/>{sending?'Envoi…':confirming?'Confirmer l’envoi':'Envoyer l’offre'}</button></footer></section></div>
}
