import { useEffect, useMemo, useState } from 'react'
import { ArrowLeftRight, Check, Coins, Search, X } from 'lucide-react'
import { queryCollection, queryFriendCollection } from './cardsApi'
import { createTrade, getFriends } from './tradeApi'
import GameCard from './GameCard'
import type { Card, Friend } from './types'

export type TradeDraft={contact?:string;requestedCards?:Card[]}

export default function TradeComposer({currentUserId,draft,onClose,onSent}:{currentUserId:string;draft?:TradeDraft;onClose:()=>void;onSent:()=>void}){
 const [friends,setFriends]=useState<Friend[]>([]);const [friend,setFriend]=useState<Friend|null>(null);const [mine,setMine]=useState<Card[]>([]);const [theirs,setTheirs]=useState<Card[]>(draft?.requestedCards??[]);const [offered,setOffered]=useState<string[]>([]);const [requested,setRequested]=useState<string[]>(draft?.requestedCards?.map(card=>card.id)??[]);const [tab,setTab]=useState<'mine'|'theirs'>('theirs');const [query,setQuery]=useState('');const [credits,setCredits]=useState(0);const [requestedCredits,setRequestedCredits]=useState(0);const [loading,setLoading]=useState(true);const [sending,setSending]=useState(false);const [error,setError]=useState('');const [confirming,setConfirming]=useState(false)
 useEffect(()=>{getFriends(currentUserId).then(items=>{setFriends(items);const initial=items.find(item=>item.username===draft?.contact)??(draft?.contact?null:items[0]??null);setFriend(initial)}).catch(()=>setError('Impossible de charger vos amis.')).finally(()=>setLoading(false))},[currentUserId,draft?.contact])
 useEffect(()=>{if(!friend)return;setLoading(true);Promise.all([queryCollection({}),queryFriendCollection(friend.username,{})]).then(([own,other])=>{setMine(own.cards);setTheirs(previous=>[...new Map([...(draft?.requestedCards??[]),...other.cards].map(card=>[card.id,card])).values()])}).catch(()=>setError('Impossible de charger les collections.')).finally(()=>setLoading(false))},[friend,draft?.requestedCards])
 const shown=useMemo(()=>{const source=tab==='mine'?mine:theirs;const normalized=query.trim().toLocaleLowerCase('fr');return normalized?source.filter(card=>`${card.title} ${card.category}`.toLocaleLowerCase('fr').includes(normalized)):source},[tab,mine,theirs,query])
 const toggle=(id:string)=>tab==='mine'?setOffered(list=>list.includes(id)?list.filter(item=>item!==id):[...list,id]):setRequested(list=>list.includes(id)?list.filter(item=>item!==id):[...list,id])
 const send=async()=>{if(!friend)return;if(!offered.length&&!requested.length&&!credits&&!requestedCredits){setError('Sélectionnez au moins une carte ou des crédits.');return}if(!confirming){setConfirming(true);return}setSending(true);setError('');try{await createTrade({recipientId:friend.id,currentUserId,offeredCardIds:offered,requestedCardIds:requested,offeredCredits:credits,requestedCredits});onSent()}catch(err){setError(err instanceof Error?err.message:'Envoi impossible.');setConfirming(false)}finally{setSending(false)}}
 if(!friend)return <div className="modal-backdrop"><section className="friend-picker" role="dialog" aria-modal="true"><button className="modal-x" onClick={onClose}><X/></button><h2>Choisir un ami</h2>{loading?<p>Chargement…</p>:friends.length?friends.map(item=><button key={item.id} onClick={()=>setFriend(item)}><i>{item.username[0]}</i>{item.username}<span>Échanger →</span></button>):<p>Aucun ami disponible.</p>}</section></div>
 return <div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className="trade-composer" role="dialog" aria-modal="true" aria-labelledby="trade-title"><header><h2 id="trade-title">Échanger avec <span>{friend.username}</span></h2><button onClick={onClose}><X/></button></header><div className="trade-summary"><b>Moi : {offered.length} carte{offered.length!==1?'s':''}{credits?` · ${credits} WB`:''}</b><ArrowLeftRight/><b>{friend.username} : {requested.length} carte{requested.length!==1?'s':''}{requestedCredits?` · ${requestedCredits} WB`:''}</b></div><nav><button className={tab==='mine'?'active':''} onClick={()=>setTab('mine')}>Mes cartes</button><button className={tab==='theirs'?'active':''} onClick={()=>setTab('theirs')}>Cartes de {friend.username}</button></nav><div className="trade-tools"><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Rechercher une carte…"/></label><label><Coins/>Moi <input type="number" min="0" max="10000" value={credits} onChange={e=>setCredits(Math.max(0,Number(e.target.value)))}/></label><label><Coins/>{friend.username} <input type="number" min="0" max="10000" value={requestedCredits} onChange={e=>setRequestedCredits(Math.max(0,Number(e.target.value)))}/></label></div>{error?<div className="api-error">{error}</div>:null}<div className="trade-card-grid">{loading?<p>Chargement des collections…</p>:shown.map(card=>{const active=(tab==='mine'?offered:requested).includes(card.id);return <button key={card.id} className={active?'selected':''} onClick={()=>toggle(card.id)}><GameCard card={card} compact/>{active?<span className="trade-check"><Check/></span>:null}</button>})}</div><footer><button onClick={onClose}>Annuler</button>{confirming?<span>Confirmer l’envoi de cette offre ?</span>:null}<button className="primary" disabled={sending} onClick={send}><ArrowLeftRight/>{sending?'Envoi…':confirming?'Confirmer l’envoi':'Envoyer l’offre'}</button></footer></section></div>
}
